
-- -- delete
-- DROP SCHEMA "APP" CASCADE;
-- DROP SCHEMA "COMMON" CASCADE;
-- DROP SCHEMA "USER" CASCADE;
-- DROP SCHEMA "LOG";
-- DROP SCHEMA "ENUM";
-- DROP SCHEMA "public" CASCADE;


-- -- create
-- CREATE SCHEMA "APP";
-- CREATE SCHEMA "COMMON";
-- CREATE SCHEMA "USER";
-- CREATE SCHEMA "LOG";
-- CREATE SCHEMA "ENUM";
-- CREATE SCHEMA "public";
